<?php

namespace Database\Seeders\dev;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class PerolehanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->master() as $datum) {
            //foreach ($this->data() as $datum) {
            $master = \App\Models\Perunding\PemantauanPerolehan::updateOrCreate([
                'pemantauan_id' => $datum['pemantauan_id'],
                'nama_perolehan' => $datum['nama_perolehan'],
                'nama_peruding' => $datum['nama_peruding'],
                'jenis_perkhidmatan' => $datum['jenis_perkhidmatan'],
                'no_documen_perolehan' => $datum['no_documen_perolehan'],
                'kaedah_perolehan' => $datum['kaedah_perolehan'],
                'no_pendaftaran_moh' => $datum['no_pendaftaran_moh'],
                'tarikh_setuju_terima' => $datum['tarikh_setuju_terima'],
                'tarikh_tamat_perjanjian' => $datum['tarikh_tamat_perjanjian'],
                'yuran_perunding' => $datum['yuran_perunding'],
                'eocp' => $datum['eocp'],
                'kemajuan_jadual' => $datum['kemajuan_jadual'],
                'kemajuan_sebenar' => $datum['kemajuan_sebenar'],
                'penilaiyan' => $datum['penilaiyan'],
                'status_pelaksanaan' => $datum['status_pelaksanaan'],
                'row_status' => $datum['row_status'],
                'dibuat_oleh' => $datum['dibuat_oleh'],
                'dikemaskini_oleh' => $datum['dikemaskini_oleh'],
            ]);
        }
    }

    public function master()
        {
            return [           
                [
                    'pemantauan_id' => '1',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'RBM ENGINEERING CONSULTANT',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                [
                    'pemantauan_id' => '1',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'TELUK BPZP',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                [
                    'pemantauan_id' => '1',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'TELUK BPZP',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],

                [
                    'pemantauan_id' => '2',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'RBM ENGINEERING CONSULTANT',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                [
                    'pemantauan_id' => '2',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'TELUK BPZP',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                [
                    'pemantauan_id' => '2',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'TELUK BPZP',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],

                [
                    'pemantauan_id' => '3',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'RBM ENGINEERING CONSULTANT',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                [
                    'pemantauan_id' => '3',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'TELUK BPZP',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                [
                    'pemantauan_id' => '3',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'TELUK BPZP',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],

                [
                    'pemantauan_id' => '4',
                    'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                    'nama_peruding' => 'RBM ENGINEERING CONSULTANT',
                    'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                    'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                    'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                    'no_pendaftaran_moh' => '002147220-D',
                    'tarikh_setuju_terima' => '2017-04-25',
                    'tarikh_tamat_perjanjian' => '2017-04-25',
                    'yuran_perunding' => '10,000,000.00	',
                    'eocp' => '2',
                    'kemajuan_jadual' => '60',
                    'kemajuan_sebenar' => '60',
                    'penilaiyan' => 'BAIK',
                    'status_pelaksanaan' => 'LEWAT JADUAL',
                    'row_status' => 1,
                    'dibuat_oleh' => 1,
                    'dikemaskini_oleh' => 1,
                ],
                // [
                //     'pemantauan_id' => '5',
                //     'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                //     'nama_peruding' => 'TELUK BPZP',
                //     'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                //     'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                //     'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                //     'no_pendaftaran_moh' => '002147220-D',
                //     'tarikh_setuju_terima' => '2017-04-25',
                //     'tarikh_tamat_perjanjian' => '2017-04-25',
                //     'yuran_perunding' => '10,000,000.00	',
                //     'eocp' => '2',
                //     'kemajuan_jadual' => '60',
                //     'kemajuan_sebenar' => '60',
                //     'penilaiyan' => 'BAIK',
                //     'status_pelaksanaan' => 'LEWAT JADUAL',
                //     'row_status' => 1,
                //     'dibuat_oleh' => 1,
                //     'dikemaskini_oleh' => 1,
                // ],
                // [
                //     'pemantauan_id' => '6',
                //     'nama_perolehan' => 'PERUNDING ARKITEK/PERUNDING M&E',
                //     'nama_peruding' => 'TELUK BPZP',
                //     'jenis_perkhidmatan' => 'KERJA FIZIKAL',
                //     'no_documen_perolehan' => 'JPS/P/PK/12/2019',
                //     'kaedah_perolehan' => 'LANTIKAN TERUS BESERTA KOS SILING',
                //     'no_pendaftaran_moh' => '002147220-D',
                //     'tarikh_setuju_terima' => '2017-04-25',
                //     'tarikh_tamat_perjanjian' => '2017-04-25',
                //     'yuran_perunding' => '10,000,000.00	',
                //     'eocp' => '2',
                //     'kemajuan_jadual' => '60',
                //     'kemajuan_sebenar' => '60',
                //     'penilaiyan' => 'BAIK',
                //     'status_pelaksanaan' => 'LEWAT JADUAL',
                //     'row_status' => 1,
                //     'dibuat_oleh' => 1,
                //     'dikemaskini_oleh' => 1,
                // ],
            ];
        }
}